const mongoose = require("mongoose");
const Question = require("./model/Question"); // adjust if your model path is different
require("dotenv").config();

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB connected for seeding...");

    // clear old questions
    await Question.deleteMany();

    // insert sample questions
    await Question.insertMany([
      // Math
{
    topic: "Math",
    difficulty: "Easy",
    question: "What is 2 + 2?",
    options: ["2", "3", "4", "5"],
    correct: "4",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 5 + 3?",
    options: ["6", "7", "8", "9"],
    correct: "8",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 10 − 4?",
    options: ["4", "5", "6", "7"],
    correct: "6",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 7 × 2?",
    options: ["12", "14", "16", "18"],
    correct: "14",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 20 ÷ 5?",
    options: ["2", "3", "4", "5"],
    correct: "4",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is the square of 6?",
    options: ["12", "24", "30", "36"],
    correct: "36",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 9 + 10?",
    options: ["18", "19", "20", "21"],
    correct: "19",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 3 × 9?",
    options: ["26", "27", "28", "29"],
    correct: "27",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 100 ÷ 20?",
    options: ["2", "3", "4", "5"],
    correct: "5",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 11 + 6?",
    options: ["15", "16", "17", "18"],
    correct: "17",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 15 − 7?",
    options: ["6", "7", "8", "9"],
    correct: "8",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is the square root of 81?",
    options: ["7", "8", "9", "10"],
    correct: "9",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 50 ÷ 10?",
    options: ["4", "5", "6", "7"],
    correct: "5",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 14 + 5?",
    options: ["17", "18", "19", "20"],
    correct: "19",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 12 × 2?",
    options: ["22", "24", "26", "28"],
    correct: "24",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 36 ÷ 6?",
    options: ["5", "6", "7", "8"],
    correct: "6",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 18 − 9?",
    options: ["9", "8", "10", "7"],
    correct: "9",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 7 + 11?",
    options: ["17", "18", "19", "20"],
    correct: "18",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 6 × 6?",
    options: ["30", "32", "34", "36"],
    correct: "36",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 25 ÷ 5?",
    options: ["3", "4", "5", "6"],
    correct: "5",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 8 + 15?",
    options: ["23", "24", "25", "26"],
    correct: "23",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 13 − 4?",
    options: ["7", "8", "9", "10"],
    correct: "9",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 4 × 8?",
    options: ["28", "30", "32", "34"],
    correct: "32",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 72 ÷ 12?",
    options: ["5", "6", "7", "8"],
    correct: "6",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 9 × 5?",
    options: ["40", "42", "44", "45"],
    correct: "45",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 19 + 3?",
    options: ["21", "22", "23", "24"],
    correct: "22",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 15 ÷ 3?",
    options: ["4", "5", "6", "7"],
    correct: "5",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 17 − 8?",
    options: ["7", "8", "9", "10"],
    correct: "9",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is 2 × 12?",
    options: ["22", "23", "24", "25"],
    correct: "24",
  },
  {
    topic: "Math",
    difficulty: "Easy",
    question: "What is the square of 5?",
    options: ["10", "20", "25", "30"],
    correct: "25",
  },
    {
    topic: "Math",
    difficulty: "Medium",
    question: "What is 12 × 8?",
    options: ["88", "96", "104", "108"],
    correct: "96",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "What is 72 ÷ 9?",
    options: ["6", "7", "8", "9"],
    correct: "8",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "Simplify: (3² + 4²).",
    options: ["7", "12", "25", "30"],
    correct: "25",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "What is the square root of 196?",
    options: ["12", "13", "14", "15"],
    correct: "14",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "Evaluate: 2(3 + 4)².",
    options: ["49", "98", "56", "78"],
    correct: "98",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "What is 7³?",
    options: ["243", "343", "512", "729"],
    correct: "343",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "What is 200 ÷ 2 ÷ 5?",
    options: ["20", "25", "30", "35"],
    correct: "20",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "If a rectangle has length 12 and width 5, what is its area?",
    options: ["50", "60", "65", "70"],
    correct: "60",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "Solve: 8² − 6².",
    options: ["12", "20", "28", "30"],
    correct: "28",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "If 5x = 30, what is x?",
    options: ["4", "5", "6", "7"],
    correct: "6",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "Simplify: (2 × 5) + (3 × 4).",
    options: ["22", "23", "24", "26"],
    correct: "22",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "Find the perimeter of a square with side 9.",
    options: ["32", "34", "36", "40"],
    correct: "36",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "What is the average of 10, 20, 30?",
    options: ["15", "20", "25", "30"],
    correct: "20",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "If 2x = 14, what is x?",
    options: ["5", "6", "7", "8"],
    correct: "7",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "What is the next prime after 19?",
    options: ["21", "23", "25", "27"],
    correct: "23",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "If 3 pencils cost 15, what is the cost of one pencil?",
    options: ["3", "4", "5", "6"],
    correct: "5",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "Find the missing number: 2, 4, 8, 16, ?",
    options: ["20", "24", "30", "32"],
    correct: "32",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "What is the LCM of 12 and 18?",
    options: ["24", "30", "36", "48"],
    correct: "36",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "Find HCF of 20 and 28.",
    options: ["2", "4", "6", "8"],
    correct: "4",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "What is the value of 3! (factorial)?",
    options: ["3", "5", "6", "9"],
    correct: "6",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "If the radius of a circle is 7, what is its diameter?",
    options: ["7", "14", "21", "28"],
    correct: "14",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "Convert 3/4 to decimal.",
    options: ["0.5", "0.6", "0.75", "0.8"],
    correct: "0.75",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "Find 40% of 200.",
    options: ["60", "70", "80", "90"],
    correct: "80",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "What is 2 to the power of 6?",
    options: ["32", "64", "128", "256"],
    correct: "64",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "What is 11 × 14?",
    options: ["144", "154", "164", "174"],
    correct: "154",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "If a triangle has sides 3, 4, 5, what type is it?",
    options: ["Equilateral", "Isosceles", "Scalene", "Right-angled"],
    correct: "Right-angled",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "Find the perimeter of a rectangle with length 10 and width 4.",
    options: ["26", "28", "30", "32"],
    correct: "28",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "If 2x + 5 = 15, what is x?",
    options: ["4", "5", "6", "7"],
    correct: "5",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "What is the sum of angles in a quadrilateral?",
    options: ["180°", "270°", "360°", "540°"],
    correct: "360°",
  },
  {
    topic: "Math",
    difficulty: "Medium",
    question: "Solve for x: x/6 = 3.",
    options: ["12", "15", "16", "18"],
    correct: "18",
  },
   {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the derivative of x²?",
    options: ["x", "2x", "x²", "2"],
    correct: "2x",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the derivative of sin(x)?",
    options: ["cos(x)", "-cos(x)", "-sin(x)", "tan(x)"],
    correct: "cos(x)",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the integral of x?",
    options: ["x²", "x²/2", "2x", "ln(x)"],
    correct: "x²/2",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the derivative of e^x?",
    options: ["1", "e", "e^x", "ln(x)"],
    correct: "e^x",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the limit as x→0 of sin(x)/x?",
    options: ["0", "1", "∞", "Undefined"],
    correct: "1",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the determinant of [[1,2],[3,4]]?",
    options: ["-2", "-1", "2", "1"],
    correct: "-2",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the second derivative of f(x) = x³?",
    options: ["6x", "3x²", "2x", "x²"],
    correct: "6x",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "Solve for x: 2x + 3 = 11.",
    options: ["3", "4", "5", "6"],
    correct: "4",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the integral of cos(x)?",
    options: ["sin(x)", "-sin(x)", "cos(x)", "-cos(x)"],
    correct: "sin(x)",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the coefficient of x² in (1 + x)^5?",
    options: ["5", "6", "10", "15"],
    correct: "10",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the value of the infinite series 1/2 + 1/4 + 1/8 + …?",
    options: ["0.5", "1", "2", "∞"],
    correct: "1",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "If log10(1000) = x, what is x?",
    options: ["2", "3", "4", "10"],
    correct: "3",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the derivative of tan(x)?",
    options: ["sec²(x)", "-sec²(x)", "cos²(x)", "sin(x)"],
    correct: "sec²(x)",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is 7! (factorial)?",
    options: ["3600", "5040", "7200", "10080"],
    correct: "5040",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "Solve: ∫ 1/x dx",
    options: ["x", "ln(x)", "x²", "1/x"],
    correct: "ln(x)",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the value of i² in complex numbers?",
    options: ["-1", "0", "1", "i"],
    correct: "-1",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "Solve: 2x² - 8 = 0.",
    options: ["±2", "±4", "±√2", "0"],
    correct: "±2",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the quadratic formula?",
    options: [
      "(-b ± √(b² - 4ac))/(2a)",
      "(-a ± √(a² - 4bc))/(2b)",
      "(b ± √(a² - 4bc))/(2a)",
      "(-b ± √(a² - 4bc))/(2c)"
    ],
    correct: "(-b ± √(b² - 4ac))/(2a)",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "If f(x) = x² + 2x + 1, what is f(−1)?",
    options: ["0", "1", "-1", "2"],
    correct: "0",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "If sin(θ) = 1/2, what is θ (0–180°)?",
    options: ["30°", "45°", "60°", "90°"],
    correct: "30°",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the limit of (1 + 1/n)^n as n → ∞?",
    options: ["1", "2.71", "∞", "0"],
    correct: "2.71",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "Differentiate f(x) = ln(x).",
    options: ["1/x", "x", "ln(x)", "x²"],
    correct: "1/x",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is eigenvalue of matrix [[2,0],[0,3]]?",
    options: ["2 and 3", "1 and 2", "3 and 4", "0 and 1"],
    correct: "2 and 3",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "Find the roots of x² − 5x + 6 = 0.",
    options: ["(2,3)", "(1,6)", "(−2,3)", "(−1,6)"],
    correct: "(2,3)",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the binomial coefficient C(6,2)?",
    options: ["12", "15", "18", "20"],
    correct: "15",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is ∫ e^x dx?",
    options: ["x·e^x", "ln(x)", "e^x", "1/e^x"],
    correct: "e^x",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is derivative of ln(sin(x))?",
    options: ["cot(x)", "csc(x)", "cos(x)/sin(x)", "1/sin(x)"],
    correct: "cot(x)",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "If a die is rolled, what is the probability of getting an even number?",
    options: ["1/2", "1/3", "2/3", "1/6"],
    correct: "1/2",
  },
  {
    topic: "Math",
    difficulty: "Hard",
    question: "What is the sum of infinite GP: 3 + 1 + 1/3 + … ?",
    options: ["4", "4.5", "5", "6"],
    correct: "4.5",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What planet is known as the Red Planet?",
    options: ["Earth", "Mars", "Jupiter", "Venus"],
    correct: "Mars",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What gas do humans exhale when they breathe out?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
    correct: "Carbon Dioxide",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What is H₂O commonly known as?",
    options: ["Water", "Salt", "Sugar", "Oxygen"],
    correct: "Water",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "How many planets are there in the solar system?",
    options: ["7", "8", "9", "10"],
    correct: "8",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What planet do we live on?",
    options: ["Mars", "Venus", "Earth", "Jupiter"],
    correct: "Earth",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "Which organ pumps blood in the human body?",
    options: ["Lungs", "Heart", "Kidneys", "Brain"],
    correct: "Heart",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "Which organ helps humans breathe?",
    options: ["Heart", "Brain", "Lungs", "Liver"],
    correct: "Lungs",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What force pulls objects toward Earth?",
    options: ["Magnetism", "Friction", "Gravity", "Electricity"],
    correct: "Gravity",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What is the center of an atom called?",
    options: ["Proton", "Neutron", "Nucleus", "Electron"],
    correct: "Nucleus",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What is the closest star to Earth?",
    options: ["Alpha Centauri", "The Moon", "The Sun", "Sirius"],
    correct: "The Sun",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What is the boiling point of water at sea level in Celsius?",
    options: ["50°C", "75°C", "100°C", "120°C"],
    correct: "100°C",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "Which gas is most abundant in Earth’s atmosphere?",
    options: ["Oxygen", "Hydrogen", "Nitrogen", "Carbon Dioxide"],
    correct: "Nitrogen",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "Which planet is famous for its rings?",
    options: ["Saturn", "Venus", "Neptune", "Mercury"],
    correct: "Saturn",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What celestial body orbits the Earth?",
    options: ["Mars", "Sun", "Moon", "Jupiter"],
    correct: "Moon",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "Which part of a plant makes food using sunlight?",
    options: ["Roots", "Stem", "Leaves", "Flowers"],
    correct: "Leaves",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What vitamin do we get from sunlight?",
    options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
    correct: "Vitamin D",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "Which celestial body is called Earth’s twin?",
    options: ["Mars", "Venus", "Jupiter", "Mercury"],
    correct: "Venus",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "How many bones are in the adult human body?",
    options: ["106", "206", "306", "406"],
    correct: "206",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What part of your body controls your thoughts?",
    options: ["Heart", "Liver", "Brain", "Lungs"],
    correct: "Brain",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "Which insect makes honey?",
    options: ["Ant", "Bee", "Fly", "Butterfly"],
    correct: "Bee",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What type of blood do mosquitoes prefer?",
    options: ["Type O", "Type A", "Type B", "Type AB"],
    correct: "Type O",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "How many continents are on Earth?",
    options: ["5", "6", "7", "8"],
    correct: "7",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What colors combine to make green?",
    options: ["Red and Yellow", "Blue and Yellow", "Red and Blue", "Blue and Black"],
    correct: "Blue and Yellow",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What animal is the largest mammal?",
    options: ["Elephant", "Blue Whale", "Shark", "Rhino"],
    correct: "Blue Whale",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What is the freezing point of water in Celsius?",
    options: ["0°C", "10°C", "32°C", "100°C"],
    correct: "0°C",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "Which sense organ allows us to see?",
    options: ["Ears", "Nose", "Eyes", "Skin"],
    correct: "Eyes",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What do bees collect from flowers?",
    options: ["Honey", "Pollen", "Seeds", "Leaves"],
    correct: "Pollen",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What shape is Earth?",
    options: ["Flat", "Round", "Oval", "Cube"],
    correct: "Round",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "What gas is essential for humans to breathe?",
    options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Helium"],
    correct: "Oxygen",
  },
  {
    topic: "Science",
    difficulty: "Easy",
    question: "Which star is also known as the morning star?",
    options: ["Sirius", "Venus", "Sun", "Mars"],
    correct: "Venus",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What is the chemical symbol for Gold?",
    options: ["G", "Au", "Ag", "Go"],
    correct: "Au",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What is the nearest planet to the Sun?",
    options: ["Venus", "Mercury", "Earth", "Mars"],
    correct: "Mercury",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What is the Earth's largest organ in humans?",
    options: ["Heart", "Skin", "Liver", "Lungs"],
    correct: "Skin",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which gas is known as laughing gas?",
    options: ["Nitrous Oxide", "Carbon Dioxide", "Oxygen", "Methane"],
    correct: "Nitrous Oxide",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Ribosome", "Mitochondria", "Cytoplasm"],
    correct: "Mitochondria",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which blood type is known as the universal donor?",
    options: ["O-", "O+", "AB+", "AB-"],
    correct: "O-",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What is the main gas found in the Sun?",
    options: ["Oxygen", "Hydrogen", "Helium", "Nitrogen"],
    correct: "Hydrogen",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What is the outermost layer of Earth called?",
    options: ["Mantle", "Core", "Crust", "Lithosphere"],
    correct: "Crust",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What part of the cell contains genetic material?",
    options: ["Mitochondria", "Nucleus", "Cytoplasm", "Ribosome"],
    correct: "Nucleus",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What type of blood cells help fight infection?",
    options: ["Red blood cells", "White blood cells", "Platelets", "Plasma"],
    correct: "White blood cells",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which planet has the most moons?",
    options: ["Earth", "Jupiter", "Saturn", "Neptune"],
    correct: "Saturn",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which element has the chemical symbol ‘Na’?",
    options: ["Sodium", "Nitrogen", "Nickel", "Neon"],
    correct: "Sodium",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which vitamin is produced when the skin is exposed to sunlight?",
    options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
    correct: "Vitamin D",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What type of star is the Sun classified as?",
    options: ["Red Giant", "White Dwarf", "Main Sequence", "Supernova"],
    correct: "Main Sequence",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which part of the plant absorbs water from soil?",
    options: ["Leaves", "Stem", "Roots", "Flower"],
    correct: "Roots",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What is the process of water changing to vapor called?",
    options: ["Evaporation", "Condensation", "Sublimation", "Precipitation"],
    correct: "Evaporation",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "How many chambers are in a human heart?",
    options: ["2", "3", "4", "5"],
    correct: "4",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What is the main function of red blood cells?",
    options: ["Clotting", "Immune Defense", "Transport Oxygen", "Store Fat"],
    correct: "Transport Oxygen",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which scientist proposed the three laws of motion?",
    options: ["Einstein", "Newton", "Galileo", "Kepler"],
    correct: "Newton",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which wave is used in mobile phone communication?",
    options: ["Microwave", "Gamma rays", "Infrared", "Ultraviolet"],
    correct: "Microwave",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What is the chemical formula of table salt?",
    options: ["NaCl", "KCl", "NaOH", "CaCO₃"],
    correct: "NaCl",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which part of the human brain controls balance?",
    options: ["Cerebrum", "Cerebellum", "Medulla", "Thalamus"],
    correct: "Cerebellum",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What type of energy is possessed by a moving body?",
    options: ["Potential Energy", "Kinetic Energy", "Thermal Energy", "Nuclear Energy"],
    correct: "Kinetic Energy",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Who developed the theory of relativity?",
    options: ["Isaac Newton", "Galileo", "Albert Einstein", "Nikola Tesla"],
    correct: "Albert Einstein",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which gas is commonly known as quicklime?",
    options: ["Calcium Oxide", "Carbon Dioxide", "Sodium Carbonate", "Ammonia"],
    correct: "Calcium Oxide",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which organ is affected by hepatitis?",
    options: ["Lungs", "Heart", "Liver", "Kidneys"],
    correct: "Liver",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What is the SI unit of force?",
    options: ["Joule", "Watt", "Newton", "Pascal"],
    correct: "Newton",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which blood cells help in clotting?",
    options: ["RBC", "WBC", "Platelets", "Plasma"],
    correct: "Platelets",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "What is the hardest natural substance on Earth?",
    options: ["Iron", "Diamond", "Steel", "Quartz"],
    correct: "Diamond",
  },
  {
    topic: "Science",
    difficulty: "Medium",
    question: "Which is the only planet that rotates on its side?",
    options: ["Uranus", "Neptune", "Saturn", "Mars"],
    correct: "Uranus",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the speed of light in vacuum?",
    options: ["3 × 10^8 m/s", "1.5 × 10^8 m/s", "3 × 10^6 m/s", "9.8 m/s²"],
    correct: "3 × 10^8 m/s",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the chemical formula of ozone?",
    options: ["O2", "O3", "O4", "CO2"],
    correct: "O3",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which particle has no electric charge?",
    options: ["Electron", "Proton", "Neutron", "Photon"],
    correct: "Neutron",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the pH of pure water at 25°C?",
    options: ["6", "7", "8", "9"],
    correct: "7",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which law states that energy cannot be created or destroyed?",
    options: [
      "First Law of Thermodynamics",
      "Second Law of Thermodynamics",
      "Law of Inertia",
      "Law of Gravitation"
    ],
    correct: "First Law of Thermodynamics",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which vitamin deficiency causes scurvy?",
    options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"],
    correct: "Vitamin C",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the unit of electric resistance?",
    options: ["Joule", "Ohm", "Ampere", "Volt"],
    correct: "Ohm",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which element has the atomic number 26?",
    options: ["Iron", "Copper", "Zinc", "Silver"],
    correct: "Iron",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Ribosome", "Mitochondria", "Chloroplast"],
    correct: "Mitochondria",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is absolute zero in Celsius?",
    options: ["0°C", "-100°C", "-273°C", "-460°C"],
    correct: "-273°C",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which blood group is known as the universal receiver?",
    options: ["A+", "B+", "O-", "AB+"],
    correct: "AB+",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the most abundant element in the universe?",
    options: ["Oxygen", "Carbon", "Hydrogen", "Helium"],
    correct: "Hydrogen",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which scientist proposed the uncertainty principle?",
    options: ["Newton", "Einstein", "Heisenberg", "Bohr"],
    correct: "Heisenberg",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which galaxy is Earth located in?",
    options: ["Andromeda", "Milky Way", "Sombrero", "Whirlpool"],
    correct: "Milky Way",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the SI unit of electric charge?",
    options: ["Coulomb", "Ampere", "Watt", "Tesla"],
    correct: "Coulomb",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which organelles are known as the garbage disposal of the cell?",
    options: ["Nucleus", "Ribosomes", "Lysosomes", "Golgi bodies"],
    correct: "Lysosomes",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which gas is used in fluorescent lamps?",
    options: ["Oxygen", "Argon", "Nitrogen", "Hydrogen"],
    correct: "Argon",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the most common isotope of Carbon?",
    options: ["Carbon-12", "Carbon-13", "Carbon-14", "Carbon-16"],
    correct: "Carbon-12",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "At what temperature are Celsius and Fahrenheit equal?",
    options: ["-40", "0", "100", "-273"],
    correct: "-40",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the chemical symbol for Tungsten?",
    options: ["Tn", "Tu", "W", "T"],
    correct: "W",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which law explains why planes can fly?",
    options: ["Newton’s Third Law", "Bernoulli’s Principle", "Archimedes’ Principle", "Conservation of Energy"],
    correct: "Bernoulli’s Principle",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which scientist discovered electrons?",
    options: ["J.J. Thomson", "Rutherford", "Bohr", "Dalton"],
    correct: "J.J. Thomson",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the 2nd most abundant gas in Earth’s atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"],
    correct: "Oxygen",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which branch of biology deals with classification of organisms?",
    options: ["Ecology", "Taxonomy", "Genetics", "Evolution"],
    correct: "Taxonomy",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the value of gravitational acceleration (g) on Earth?",
    options: ["8.9 m/s²", "9.8 m/s²", "10.5 m/s²", "12 m/s²"],
    correct: "9.8 m/s²",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which planet has the highest surface temperature?",
    options: ["Mars", "Venus", "Mercury", "Jupiter"],
    correct: "Venus",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which organ in humans produces insulin?",
    options: ["Liver", "Pancreas", "Kidneys", "Stomach"],
    correct: "Pancreas",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "What is the SI unit of pressure?",
    options: ["Newton", "Watt", "Pascal", "Joule"],
    correct: "Pascal",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which scientist is known as the father of genetics?",
    options: ["Charles Darwin", "Mendel", "Watson", "Crick"],
    correct: "Mendel",
  },
  {
    topic: "Science",
    difficulty: "Hard",
    question: "Which planet has a day longer than its year?",
    options: ["Mercury", "Venus", "Saturn", "Jupiter"],
    correct: "Venus",
  },
   {
    topic: "History",
    difficulty: "Easy",
    question: "Who was the first President of the United States?",
    options: ["George Washington", "Abraham Lincoln", "John Adams", "Thomas Jefferson"],
    correct: "George Washington",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was the first Prime Minister of India?",
    options: ["Sardar Patel", "Jawaharlal Nehru", "Mahatma Gandhi", "Rajendra Prasad"],
    correct: "Jawaharlal Nehru",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "In which year did World War II end?",
    options: ["1942", "1945", "1948", "1950"],
    correct: "1945",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was the first man to step on the Moon?",
    options: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"],
    correct: "Neil Armstrong",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "The Great Wall of China was built to protect against which group?",
    options: ["Mongols", "Romans", "Vikings", "Persians"],
    correct: "Mongols",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who discovered America in 1492?",
    options: ["Christopher Columbus", "Magellan", "Marco Polo", "Cook"],
    correct: "Christopher Columbus",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was the first emperor of Rome?",
    options: ["Julius Caesar", "Augustus", "Nero", "Marcus Aurelius"],
    correct: "Augustus",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was the famous queen of ancient Egypt?",
    options: ["Cleopatra", "Nefertiti", "Hatshepsut", "Isis"],
    correct: "Cleopatra",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "The Taj Mahal was built by which Mughal emperor?",
    options: ["Akbar", "Jahangir", "Shah Jahan", "Aurangzeb"],
    correct: "Shah Jahan",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was the first President of India?",
    options: ["Rajendra Prasad", "Sarvepalli Radhakrishnan", "Zakir Hussain", "V.V. Giri"],
    correct: "Rajendra Prasad",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Which country gifted the Statue of Liberty to the USA?",
    options: ["France", "England", "Spain", "Germany"],
    correct: "France",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "In which country did the Industrial Revolution begin?",
    options: ["USA", "France", "Germany", "England"],
    correct: "England",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was the first human to travel into space?",
    options: ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "Valentina Tereshkova"],
    correct: "Yuri Gagarin",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was known as the Iron Lady?",
    options: ["Margaret Thatcher", "Indira Gandhi", "Golda Meir", "Angela Merkel"],
    correct: "Margaret Thatcher",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who wrote the Indian national anthem?",
    options: ["Rabindranath Tagore", "Bankim Chandra Chatterjee", "M.K. Gandhi", "Subhas Chandra Bose"],
    correct: "Rabindranath Tagore",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "When did India gain independence?",
    options: ["1942", "1945", "1947", "1950"],
    correct: "1947",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was the first woman Prime Minister of India?",
    options: ["Sarojini Naidu", "Indira Gandhi", "Pratibha Patil", "Sonia Gandhi"],
    correct: "Indira Gandhi",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was known as the Father of the Nation in India?",
    options: ["Jawaharlal Nehru", "Subhas Chandra Bose", "Mahatma Gandhi", "B. R. Ambedkar"],
    correct: "Mahatma Gandhi",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "What is the capital of ancient Rome?",
    options: ["Athens", "Rome", "Constantinople", "Alexandria"],
    correct: "Rome",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Which country was ruled by the Pharaohs?",
    options: ["Greece", "Rome", "Egypt", "Persia"],
    correct: "Egypt",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was the first US President to live in the White House?",
    options: ["John Adams", "Thomas Jefferson", "James Madison", "George Washington"],
    correct: "John Adams",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who invented the telephone?",
    options: ["Alexander Graham Bell", "Thomas Edison", "James Watt", "Nikola Tesla"],
    correct: "Alexander Graham Bell",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Which empire built the Colosseum?",
    options: ["Greek", "Roman", "Persian", "Byzantine"],
    correct: "Roman",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "The Berlin Wall divided which city?",
    options: ["London", "Paris", "Berlin", "Moscow"],
    correct: "Berlin",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was the first Governor-General of independent India?",
    options: ["Rajagopalachari", "Lord Louis Mountbatten", "Rajendra Prasad", "Sardar Patel"],
    correct: "Lord Louis Mountbatten",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who discovered the sea route to India?",
    options: ["Columbus", "Vasco da Gama", "Magellan", "Marco Polo"],
    correct: "Vasco da Gama",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Which war was fought between the North and South regions in the USA?",
    options: ["Cold War", "American Civil War", "World War I", "Revolutionary War"],
    correct: "American Civil War",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Who was India’s first woman President?",
    options: ["Indira Gandhi", "Sarojini Naidu", "Pratibha Patil", "Sonia Gandhi"],
    correct: "Pratibha Patil",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Which famous leader delivered the speech 'I Have a Dream'?",
    options: ["Abraham Lincoln", "Martin Luther King Jr.", "Nelson Mandela", "Barack Obama"],
    correct: "Martin Luther King Jr.",
  },
  {
    topic: "History",
    difficulty: "Easy",
    question: "Which empire built Machu Picchu?",
    options: ["Maya", "Inca", "Aztec", "Roman"],
    correct: "Inca",
  },
    {
    topic: "History",
    difficulty: "Medium",
    question: "In which year did World War II begin?",
    options: ["1938", "1939", "1940", "1941"],
    correct: "1939",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who was the British Prime Minister during most of World War II?",
    options: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Stanley Baldwin"],
    correct: "Winston Churchill",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "The Renaissance began in which country?",
    options: ["France", "England", "Italy", "Germany"],
    correct: "Italy",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who was the leader of the Soviet Union during World War II?",
    options: ["Vladimir Lenin", "Joseph Stalin", "Leon Trotsky", "Nikita Khrushchev"],
    correct: "Joseph Stalin",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "What was the main cause of the Cold War?",
    options: ["Territorial disputes", "Economic rivalry", "Ideological differences", "Religious conflicts"],
    correct: "Ideological differences",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Which empire was ruled by Genghis Khan?",
    options: ["Roman Empire", "Mongol Empire", "Ottoman Empire", "Persian Empire"],
    correct: "Mongol Empire",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who wrote the Declaration of Independence?",
    options: ["Benjamin Franklin", "George Washington", "Thomas Jefferson", "John Adams"],
    correct: "Thomas Jefferson",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "When did the French Revolution start?",
    options: ["1787", "1789", "1791", "1793"],
    correct: "1789",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Which treaty ended World War I?",
    options: ["Treaty of Versailles", "Treaty of Paris", "Treaty of Tordesillas", "Treaty of Utrecht"],
    correct: "Treaty of Versailles",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who was the longest-reigning British monarch before Queen Elizabeth II?",
    options: ["King George III", "Queen Victoria", "King Henry VIII", "Queen Anne"],
    correct: "Queen Victoria",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Which ancient civilization built the city of Machu Picchu?",
    options: ["Aztec", "Maya", "Inca", "Olmec"],
    correct: "Inca",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who was the first Chancellor of Germany in 1871?",
    options: ["Otto von Bismarck", "Wilhelm II", "Friedrich Ebert", "Kaiser Wilhelm I"],
    correct: "Otto von Bismarck",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Which war was fought between the North and South regions in the USA?",
    options: ["American Civil War", "Revolutionary War", "World War I", "War of 1812"],
    correct: "American Civil War",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "What was the primary language of the Roman Empire?",
    options: ["Greek", "Latin", "Hebrew", "Aramaic"],
    correct: "Latin",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who was the founder of the Mughal Empire in India?",
    options: ["Babur", "Akbar", "Shah Jahan", "Aurangzeb"],
    correct: "Babur",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "When did India become a republic?",
    options: ["1947", "1950", "1952", "1960"],
    correct: "1950",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who was the leader of the Indian independence movement advocating non-violence?",
    options: ["Bhagat Singh", "Jawaharlal Nehru", "Subhas Chandra Bose", "Mahatma Gandhi"],
    correct: "Mahatma Gandhi",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "The Berlin Wall fell in which year?",
    options: ["1987", "1989", "1991", "1993"],
    correct: "1989",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who was the President of the Confederate States during the American Civil War?",
    options: ["Robert E. Lee", "Stonewall Jackson", "Jefferson Davis", "Ulysses S. Grant"],
    correct: "Jefferson Davis",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who painted the ceiling of the Sistine Chapel?",
    options: ["Leonardo da Vinci", "Raphael", "Michelangelo", "Donatello"],
    correct: "Michelangelo",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Which country was the first to grant women the right to vote?",
    options: ["USA", "New Zealand", "UK", "France"],
    correct: "New Zealand",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Which event sparked the start of World War I?",
    options: ["Assassination of Archduke Franz Ferdinand", "Invasion of Poland", "Battle of the Somme", "Treaty of Versailles"],
    correct: "Assassination of Archduke Franz Ferdinand",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who was the ancient Greek philosopher known for his method of questioning?",
    options: ["Plato", "Socrates", "Aristotle", "Pythagoras"],
    correct: "Socrates",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "What is the significance of July 14 in French history?",
    options: ["Start of the Renaissance", "Storming of the Bastille", "End of World War II", "French Revolution Begins"],
    correct: "Storming of the Bastille",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who was the last Pharaoh of ancient Egypt?",
    options: ["Cleopatra VII", "Tutankhamun", "Ramses II", "Nefertiti"],
    correct: "Cleopatra VII",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Which explorer is credited with circumnavigating the globe?",
    options: ["Vasco da Gama", "Christopher Columbus", "Ferdinand Magellan", "James Cook"],
    correct: "Ferdinand Magellan",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "What was the main cause of the fall of the Roman Empire?",
    options: ["Economic troubles", "Invasions by Barbarian tribes", "Political corruption", "All of the above"],
    correct: "All of the above",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who was known as the 'Maid of Orléans'?",
    options: ["Joan of Arc", "Marie Antoinette", "Catherine the Great", "Queen Elizabeth I"],
    correct: "Joan of Arc",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Which movement was led by Martin Luther in the 16th century?",
    options: ["The Enlightenment", "The Protestant Reformation", "The Renaissance", "The Industrial Revolution"],
    correct: "The Protestant Reformation",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "Who was the first Emperor of China?",
    options: ["Qin Shi Huang", "Liu Bang", "Kublai Khan", "Sun Yat-sen"],
    correct: "Qin Shi Huang",
  },
  {
    topic: "History",
    difficulty: "Medium",
    question: "What was the primary language spoken in the Byzantine Empire?",
    options: ["Latin", "Greek", "Aramaic", "Hebrew"],
    correct: "Greek",
  },
   {
    topic: "History",
    difficulty: "Hard",
    question: "Who was the first emperor of Rome?",
    options: ["Julius Caesar", "Augustus", "Nero", "Marcus Aurelius"],
    correct: "Augustus",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "When was the Magna Carta signed?",
    options: ["1215", "1315", "1415", "1515"],
    correct: "1215",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Who was the Byzantine Emperor during the Nika riots?",
    options: ["Justinian I", "Heraclius", "Constantine", "Theodosius I"],
    correct: "Justinian I",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "What was the primary cause of the Thirty Years’ War?",
    options: ["Religious conflict", "Territorial expansion", "Political rivalry", "Economic crises"],
    correct: "Religious conflict",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Who was the founder of the Ottoman Empire?",
    options: ["Mehmed II", "Osman I", "Suleiman the Magnificent", "Bayezid I"],
    correct: "Osman I",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "What was the main economic system in medieval Europe?",
    options: ["Capitalism", "Feudalism", "Socialism", "Mercantilism"],
    correct: "Feudalism",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Which empire collapsed after the Battle of Manzikert in 1071?",
    options: ["Byzantine Empire", "Ottoman Empire", "Holy Roman Empire", "Mongol Empire"],
    correct: "Byzantine Empire",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "The Treaty of Westphalia, ending which conflict, was signed in 1648?",
    options: ["Hundred Years’ War", "Thirty Years’ War", "Seven Years’ War", "War of Spanish Succession"],
    correct: "Thirty Years’ War",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Who led the Haitian Revolution?",
    options: ["Toussaint Louverture", "Jean-Jacques Dessalines", "Henri Christophe", "Alexandre Pétion"],
    correct: "Toussaint Louverture",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "What innovation is Johannes Gutenberg famous for?",
    options: ["Printing press", "Compass", "Steam engine", "Telescope"],
    correct: "Printing press",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Who was the ruler of the Mongol Empire during its greatest expansion?",
    options: ["Genghis Khan", "Kublai Khan", "Ogedei Khan", "Batu Khan"],
    correct: "Genghis Khan",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Which revolution marked the rise of Napoleon Bonaparte?",
    options: ["French Revolution", "Russian Revolution", "American Revolution", "Industrial Revolution"],
    correct: "French Revolution",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Who was the longest-reigning monarch of the Habsburg dynasty?",
    options: ["Maria Theresa", "Franz Joseph I", "Charles V", "Maximilian I"],
    correct: "Franz Joseph I",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Which battle is considered Napoleon’s final defeat?",
    options: ["Battle of Leipzig", "Battle of Trafalgar", "Battle of Waterloo", "Battle of Austerlitz"],
    correct: "Battle of Waterloo",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Who was the primary author of the US Constitution’s Bill of Rights?",
    options: ["Thomas Jefferson", "James Madison", "Alexander Hamilton", "Benjamin Franklin"],
    correct: "James Madison",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "What was the code of laws created by Emperor Justinian I called?",
    options: ["Justinian Code", "Code of Hammurabi", "Napoleonic Code", "Code of Ur-Nammu"],
    correct: "Justinian Code",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "During which century did the Black Death devastate Europe?",
    options: ["12th", "13th", "14th", "15th"],
    correct: "14th",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Who was the leader of the Bolsheviks during the Russian Revolution?",
    options: ["Leon Trotsky", "Joseph Stalin", "Vladimir Lenin", "Nicholas II"],
    correct: "Vladimir Lenin",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "The Reconquista was the Christian effort to retake which territory?",
    options: ["Italy", "France", "Spain", "Portugal"],
    correct: "Spain",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Which empire was ruled by Shah Jahan?",
    options: ["Mughal Empire", "Ottoman Empire", "Safavid Empire", "Maurya Empire"],
    correct: "Mughal Empire",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Who discovered the Rosetta Stone, key to deciphering Egyptian hieroglyphs?",
    options: ["Jean-François Champollion", "Napoleon Bonaparte", "Howard Carter", "Giovanni Belzoni"],
    correct: "Giovanni Belzoni",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Which French king was executed during the French Revolution?",
    options: ["Louis XIV", "Louis XV", "Louis XVI", "Louis XVIII"],
    correct: "Louis XVI",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Which empire was ruled by Suleiman the Magnificent?",
    options: ["Mughal", "Byzantine", "Ottoman", "Roman"],
    correct: "Ottoman",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "What was the first permanent English settlement in America?",
    options: ["Plymouth", "Roanoke", "Jamestown", "Salem"],
    correct: "Jamestown",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Who was the founder of the Sikh religion?",
    options: ["Guru Nanak", "Guru Gobind Singh", "Guru Arjan", "Guru Tegh Bahadur"],
    correct: "Guru Nanak",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Which philosopher wrote 'The Prince'?",
    options: ["Machiavelli", "Descartes", "Spinoza", "Locke"],
    correct: "Machiavelli",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Which treaty ended the Napoleonic Wars?",
    options: ["Treaty of Versailles", "Treaty of Ghent", "Congress of Vienna", "Treaty of Paris (1815)"],
    correct: "Treaty of Paris (1815)",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "During which event was the Bastille stormed?",
    options: ["French Revolution", "American Revolution", "Russian Revolution", "English Civil War"],
    correct: "French Revolution",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Who was the Egyptian queen known for her relationships with Julius Caesar and Mark Antony?",
    options: ["Nefertiti", "Cleopatra", "Hatshepsut", "Isis"],
    correct: "Cleopatra",
  },
  {
    topic: "History",
    difficulty: "Hard",
    question: "Which dynasty built the Forbidden City in China?",
    options: ["Ming", "Qing", "Tang", "Han"],
    correct: "Ming",
  }



]);

    console.log("🎉 Questions seeded successfully!");
    process.exit();
  } catch (err) {
    console.error("❌ Error seeding questions:", err);
    process.exit(1);
  }
};

seed();
